### ISSUE TITLE
error  undefined is not an object（evaluating cameramanage.aspect）

### ISSUE THREAD

**Issue by AboutCXJ** [cpunion/react-native-barcode-scanner-universal#13]
error  undefined is not an object（evaluating cameramanage.aspect）
 
I have performed the command
rnpm link react-native-camera
rnpm link react-native-barcodescanner

**Comment by aizhaodangning** [comment]
i got the same error on iOS, Need help

**Comment by cpunion** [comment]
@AboutCXJ @aizhaodangning Sorry for late. This library will deprecate, and `react-native-camera` supports both iOS and Android now, please try it.

Thanks.
