### ISSUE TITLE
Warning: Native component for "RNBarcodeScannerView" does not exist

### ISSUE THREAD

**Issue by einicher** [cpunion/react-native-barcode-scanner-universal#3]
Does this mean, the android phone does not support a used native Library?

**Comment by cpunion** [comment]
Did you link the native library into your project? See https://github.com/applean/react-native-barcode-scanner-universal#install .

**Comment by einicher** [comment]
Yes, problem is installing of react-native-barcodescanner is very complicated since it has native java dependencies.

**Comment by cpunion** [comment]
@einicher Did you solve the problem? `rnpm` can simplify linking native libraries.

**Comment by einicher** [comment]
no, i moved completly to native script. its more stable and beginner friendly.
