### ISSUE TITLE
app crashes in ios version 9.3.2

### ISSUE THREAD

**Issue by shaikhussian** [cpunion/react-native-barcode-scanner-universal#4]
barcode scanner is crashes in ios **version:9.3.2** using **react-native version:0.25.1** and r**eact-native-barcode-scanner-universal version:1.0.5** may i know that what is the problem

**Comment by cpunion** [comment]
Could you please provide the stacktrace in Debug environment? My app is working fine on **iOS 9.3.2**, but using **react-native@0.26.2**.

**Comment by shaikhussian** [comment]
@cpunion this was crash report which i got in device

`Jun  9 16:07:05 6-silver Project[1303] <Notice>: Error setting property 'captureAudio' of RCTCamera with tag #168: capturing audio
Jun  9 16:07:05 6-silver Project[1303] <Warning>: Error Domain=AVFoundationErrorDomain Code=-11852 "Cannot use Back Camera" UserInfo={NSLocalizedDescription=Cannot use Back Camera, NSLocalizedFailureReason=This app is not authorized to use Back Camera., AVErrorDeviceKey=<AVCaptureFigVideoDevice: 0x1281bd7d0 [Back Camera][com.apple.avfoundation.avcapturedevice.built-in_video:0]>}
Jun  9 16:07:05 6-silver Project[1303] <Error>: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureMetadataOutput setMetadataObjectTypes:] - unsupported type found.  Use -availableMetadataObjectTypes.'
	*** First throw call stack:
	(0x1823aedb0 0x181a13f80 0x188b4ef68 0x100221488 0x181df94bc 0x181df947c 0x181e054c0 0x181dfcf80 0x181df947c 0x181e07914 0x181e070b0 0x182011470 0x182011020)
Jun  9 16:07:05 6-silver SpringBoard[58] <Warning>: HW kbd: Failed to set (null) as keyboard focus
Jun  9 16:07:05 6-silver mediaserverd[28] <Notice>: '' com.myapp.project(pid = 1303) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_PresenceScan
Jun  9 16:07:05 6-silver mediaserverd[28] <Notice>: '' com.app.project(pid = 1303) setting DiscoveryMode = DiscoveryMode_None, currentDiscoveryMode = DiscoveryMode_PresenceScan
Jun  9 16:07:05 6-silver com.apple.xpc.launchd[1] (UIKitApplication:com.app.project[0x6c4a][1303]) <Notice>: Service exited due to signal: Abort trap: 6
Jun  9 16:07:05 6-silver diagnosticd[686] <Error>: unable to find offset 0x81e20aac in shared cache for arch 'arm64'
Jun  9 16:07:05 6-silver ReportCrash[1305] <Notice>: platform_thread_get_unique_id matched 245441
Jun  9 16:07:05 6-silver ReportCrash[1305] <Notice>: Formulating report for corpse[1303] Project
Jun  9 16:07:05 6-silver SpringBoard[58] <Warning>: Application 'UIKitApplication:com.app.project[0x6c4a]' crashed.
Jun  9 16:07:05 6-silver UserEventAgent[26] <Warning>: 930389458549: id=com.app.project pid=1303, state=0
Jun  9 16:07:05 6-silver ReportCrash[1305] <Warning>: Saved type '109(109_Project)’ report (2 of max 25) at /var/mobile/Library/Logs/CrashReporter/Project-2016-06-09-160705.ips
`

**Comment by cpunion** [comment]
This library used **react-native-camera** as iOS implementation, so you should detect camera authorization on iOS. see https://github.com/lwansbrough/react-native-camera/blob/bff819c574eb60a1ffdb664aa2b03d9d15c57c28/README.md#cameracheckdeviceauthorizationstatus-promise
