### ISSUE TITLE
Dependencies greatly out of date

### ISSUE THREAD

**Issue by derdav3** [cpunion/react-native-barcode-scanner-universal#7]
It installs react-native-barcodescanner 1.0.1 which doesn't work with RN >=0.29

**Comment by ThaJay** [comment]
+1
I just got this.
Did android first, then changed to universal to do ios, but now coming back to android it's broken because of this.

> React Native dependencies
> 
>     Version 0.1.4 for React Native <=0.18
>     Version 1.x.x for React Native >=0.19
>     Version 3.x.x for React Native >=0.25
source: [react-native-barcodescanner](https://github.com/ideacreation/react-native-barcodescanner)

Willing to help, I'll take a look at the files in a bit.

**Comment by derdav3** [comment]
there were breaking changes in 0.29, that's why the installation fails.. in the package.json file there's a dependency to a forked version.. no idea how to change that to a newer release (e.g. 2.0)

**Comment by ThaJay** [comment]
if this is not easy / fast I will just make `.ios.js` and `.android.js` files and implement react-native camera myself after all.

**Comment by derdav3** [comment]
It should be very easy - I'll try in a few hours.. need to fix sth else first

**Comment by derdav3** [comment]
@ThaJay I updated the dependencies.. so this should install the newest versions from both:  
npm install derdav3/react-native-barcode-scanner-universal 

but not at all tested..

**Comment by derdav3** [comment]
I had to link `rnpm link react-native-barcodescanner` seperately... just `rnpm link` weirdly didn't do the trick... will test later

**Comment by ThaJay** [comment]
Nice, quite a bit faster than I would have done it as I have no experience with module package files yet.
I'll give it a go. Are you making this a pr?

**Comment by derdav3** [comment]
Hm if it really works why not.. But considering that the last commit is months old I doubt it'll get accepted soon

**Comment by derdav3** [comment]
I solved it on my end and did a pull request. Strangely the registering of react-native-barcodescanner didn't work automatically - I had to do it manually, but this certainly isn't a problem of scanner-universal.

**Comment by ThaJay** [comment]
Yep, seems to work here. I'll assume for now it'll work on ios as well as there haven't been changes on that side.

Looking at your change, you changed the commit hash this depends on? is it also possible to lock it on a main version so minor updates are used, like in a top level package.json using ^?

I remember that bug when I implemented react-native-barcodescanner. But not really a problem indeed, just an annoyance.

and yes this repo looks really dead. Should the creator not show up I'll happily keep using your fork, especially if you put it on npm and keep it up to date.

**Comment by derdav3** [comment]
Yes sure that's possible - I edited it the pullrequest accordingly...
let's wait a few days. if he doesn't show up I'll put it up.

**Comment by cpunion** [comment]
Thanks @derdav3 @ThaJay for your discussion, and I never thought someone used this module :-).

Thanks @derdav3, I'll check this problem and test you PR.

**Comment by cpunion** [comment]
Add Travis-CI configuration in `add-travis` branch, it built success. https://travis-ci.org/cpunion/react-native-barcode-scanner-universal/jobs/159493585

@derdav3 what it the problem on RN 0.29+? on iOS or Android? Our project used it with RN 0.30, and works fine.

**Comment by derdav3** [comment]
@cpunion Hm I don't know if it only was the wrong installation of react-native-barcodescanner. I installed the newer versions from my fork and then corrected the installation. Maybe just as well works without the update. feel free to close

**Comment by cpunion** [comment]
Thanks @derdav3 , feel free to reopen if you can reproduce. I will test your PR to upgrade dependency libraries later.

**Comment by ThaJay** [comment]
Great work!
I only had the version mismatch, so all good on this side.
